### ISSUE TITLE
include an open license in the codebase

### ISSUE THREAD

**Issue by xolotl** [whatsthealgorithm/whatsthealgorithm#3]
Great interactive!

It looks like you are wanting to openly license the project, but require an attribution to its authors. But I don't see a formal open license for the work. Having a formal license in the work would help users understand your goals and desires for the reuse of your work. If I missed the license, my apologies!

If the material were just content, you might meet your licensing goals with something like a [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) license. However, [CC doesn't recommend its licenses for software](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software), which are usually better licensed with open source software licenses. I know less about open source software licenses, but using resources from [FSF](https://www.fsf.org/) and [OSI](https://opensource.org/) might help you make a choice. [This discussion](https://opensource.stackexchange.com/questions/8161/license-that-requires-attribution-to-end-users) includes some detail on how different open source software licenses require attribution. Another option might be to license the content and code in the project separately, but that might be more complex for you and reusers.

GitHub also has [templates and suggested practices for different licensing options](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository).

**Comment by AliaElKattan** [comment]
great point, thank you for this Nate!

**Comment by xolotl** [comment]
Looks great! Ideally the license statement here would link to the license, eg: https://creativecommons.org/licenses/by-nc/4.0/

**Comment by AliaElKattan** [comment]
done :) appreciate you!
